name: Build RPI Server -PR

on: [pull_request, push]
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.13.0]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build --if-present  
      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: git@github.com:peaqnetwork/peaq-rpi-server-build.git
          BRANCH: ${{ github.head_ref }}
          FOLDER: build/
          SSH_PRIVATE_KEY: ${{ secrets.RPISERVERKEY }}
 
